### PR TITLE
Make seccomp conditional on --disable-syscall-filter

### PR DESCRIPTION
**Pull request by pwaller**
This should enable building on arches which lack seccomp.

Tested by setting the filename to something invalid on my system..

### CODE REVIEW

**Comment by djui** [comment]
Good progress. Now I have to check why it says I don't have libpoppler installed:

```
$ ./waf configure --disable-syscall-filter
Setting top to                           : /Users/uwe/dev/scraperwiki/pdf2msgpack
Setting out to                           : /Users/uwe/dev/scraperwiki/pdf2msgpack/build
Checking for 'clang++' (C++ compiler)    : /usr/bin/clang++
Checking for compiler flags --std=c++14  : yes
Checking linux-headers & seccomp support : not found
Building dynamic binaries                : yes
Checking for program 'pkg-config'        : /usr/local/bin/pkg-config
Checking for 'poppler'                   : yes
Checking libpoppler-private-dev (poppler configured with --enable-xpdf-headers) : not found
The configuration failed
(complete log in /Users/uwe/dev/scraperwiki/pdf2msgpack/build/config.log)
```

**Comment by pwaller** [comment]
So you need a poppler built with `--enable-xpdf-headers`. On Ubuntu that means installing `libpoppler-private-dev`.

**Comment by pwaller** [comment]
In case you want to search your filesystem or some package repository, the files you need installed (and visible to the compiler) include `PDFDoc.h`.

**Comment by djui** [comment]
I installed it with `--enable-xpdf-headers` and got no errors. The `PDFDoc.h` also exists ( `/usr/local/Cellar/poppler/0.45.0/include/poppler/PDFDoc.h`). I assume it doesn't look in the non-standard include path.

**Comment by pwaller** [comment]
Configure waf with:

```
CXXFLAGS=-I/usr/local/Cellar/poppler/0.45.0/include ./waf configure
```

**Comment by djui** [comment]
No luck for:

```
CXXFLAGS=-I/usr/local/Cellar/poppler/0.45.0/include ./waf configure --disable-syscall-filter
CXXFLAGS=-I/usr/local/Cellar/poppler/0.45.0/include/poppler ./waf configure --disable-syscall-filter
```

**Comment by djui** [comment]
I think the actual error is shadowed:

```
[1/2] Compiling ^[[32mbuild/.conf_check_79213a8b46bb6c99d18bd51ccf33c314/test.cpp^[[0m

  ['/usr/bin/clang++', '-I/usr/local/Cellar/poppler/0.45.0/include', '-g', '-Wall', '-Werror', '-ansi', '--std=c++14', '-I/usr/local/Cellar/poppler/0.45.0/include/poppler', '-DHAVE_POPPLE$
  err: In file included from ../test.cpp:1:
  In file included from /usr/local/Cellar/poppler/0.45.0/include/poppler/PDFDoc.h:48:
  In file included from /usr/local/Cellar/poppler/0.45.0/include/poppler/XRef.h:41:
  In file included from /usr/local/Cellar/poppler/0.45.0/include/poppler/Object.h:42:
  /usr/local/Cellar/poppler/0.45.0/include/poppler/goo/GooString.h:179:12: error: private field 'c' is not used [-Werror,-Wunused-private-field]
        char c[sizeof(char*)];
             ^
  /usr/local/Cellar/poppler/0.45.0/include/poppler/goo/GooString.h:180:11: error: private field 'i' is not used [-Werror,-Wunused-private-field]
        int i;
            ^
  /usr/local/Cellar/poppler/0.45.0/include/poppler/goo/GooString.h:181:13: error: private field 's' is not used [-Werror,-Wunused-private-field]
        char* s;
              ^
  3 errors generated.

  from /Users/uwe/dev/scraperwiki/pdf2msgpack: Test does not build: Traceback (most recent call last):
    File "/Users/uwe/dev/scraperwiki/pdf2msgpack/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Configure.py", line 335, in run_build
      bld.compile()
    File "/Users/uwe/dev/scraperwiki/pdf2msgpack/.waf3-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Build.py", line 185, in compile
      raise Errors.BuildError(self.producer.error)
  waflib.Errors.BuildError: Build failed
   -> task in 'testprog' failed (exit status 1):
      {task 4414139808: cxx test.cpp -> test.cpp.1.o}
  ['/usr/bin/clang++', '-I/usr/local/Cellar/poppler/0.45.0/include', '-g', '-Wall', '-Werror', '-ansi', '--std=c++14', '-I/usr/local/Cellar/poppler/0.45.0/include/poppler', '-DHAVE_POPPLE$

  not found
  from /Users/uwe/dev/scraperwiki/pdf2msgpack: The configuration failed

```

**Comment by pwaller** [comment]
Please try removing `-Werror` from `wscript`.

**Comment by pwaller** [comment]
BTW we should have this discussion on #21 and merge this one, since this PR is complete.

**Comment by djui** [comment]
Prematurely closed this pull-request. `waf build` fails:

```
./waf build
Waf: Entering directory `/Users/uwe/dev/scraperwiki/pdf2msgpack/build'
[1/2] Compiling src/main.cpp
../src/main.cpp:7:10: fatal error: 'linux/seccomp.h' file not found
#include <linux/seccomp.h>
         ^
1 error generated.
```

**Comment by pwaller** [comment]
D'oh. :)

**Pull request merged**
