### PR TITLE
Use fixed-size ints in msgpack

### LINKED ISSUE #26: Use pack_fix_intXX to ensure fixed encoding size for integers
While decoding using tinylib/msgp, we discovered that msgpack-c may change the type encoded on the wire, depending on the value being encoded. Unfortunately [tinylib/msgp](https://github.com/tinylib/msgp/issues/134) doesn't support this.

The easiest fix without tinylib/msgp's co-operation is to just use a fixed output encoding. This means we have to be careful wherever we encode integers.

See also: https://github.com/msgpack/msgpack-c/issues/247#issuecomment-89218884

### PR DESCRIPTION
**Pull request by pwaller**
These are all the significnat cases I could find where we write ints to the wire.

Fixes #26.

# ~~Requires rebase after #27~~

# ~~Requires more testing by @pwaller.~~

### CODE REVIEW

**Comment by djui** [comment]
Rebased.

**Comment by pwaller** [comment]
OK, I have tested this end-to-end and it works as expected, so I'm happy for it to go in.

**Comment by pwaller** [comment]
I added these files which helped:

https://github.com/scraperwiki/pdftables-test-data/commit/c3ee0a6fa0913293696b5359d0c555b4cdce0797

**Comment by pwaller** [comment]
Going to proceed with this and cut a release now.

**Pull request merged**
